name: speech_battle
description: A speech recognition game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.0
  js: ^0.6.5
  permission_handler: ^11.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/phrases.json
    - assets/heroes.json
    - assets/opponents.json
    - assets/campaign_levels.json
    - assets/training_cards.json
